# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 703)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/png/program.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"                background-color: #2E3440; /* Dark Nordic background */\n"
"            }\n"
"            QGroupBox {\n"
"                background-color: #3B4252; /* Slightly lighter Nordic background for group boxes */\n"
"                border: 1px solid #4C566A;\n"
"                border-radius: 8px;\n"
"                margin-top: 1ex; /* Space for title */\n"
"                font-weight: bold;\n"
"                color: #ECEFF4; /* Light text for titles */\n"
"            }\n"
"            QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                subcontrol-position: top center;\n"
"                padding: 0 5px;\n"
"                background-color: #434C5E;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QLabel {\n"
"                color: #D8DEE9; /* Light gray text */\n"
"                font-size: 8pt;\n"
"            }\n"
"            QLabel#label_img, QLabel#label_img_predicted {\n"
"                border: 2px solid #4C566A;\n"
"                border-radius: 6px;\n"
"                background-color: #434C5E; /* Background for image areas */\n"
"            }\n"
"            QPushButton {\n"
"                background-color: #5E81AC; /* Nordic blue for buttons */\n"
"                color: #ECEFF4; /* Light text on buttons */\n"
"                border: none;\n"
"                padding: 8px 16px;\n"
"                border-radius: 4px;\n"
"                font-size: 8pt;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1; /* Lighter blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #4C566A; /* Darker blue when pressed */\n"
"            }\n"
"            QTextEdit, QTextBrowser {\n"
"                background-color: #3B4252;\n"
"                color: #D8DEE9;\n"
"                border: 1px solid #4C566A;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 10pt;\n"
"            }\n"
"            QListWidget {\n"
"                background-color: #3B4252;\n"
"                color: #D8DEE9;\n"
"                border: 1px solid #4C566A;\n"
"                border-radius: 4px;\n"
"                font-size: 8pt;\n"
"                alternate-background-color: #434C5E; /* For alternating row colors if enabled */\n"
"            }\n"
"            QListWidget::item {\n"
"                padding: 5px;\n"
"            }\n"
"            QListWidget::item:selected {\n"
"                background-color: #5E81AC; /* Selection color */\n"
"                color: #ECEFF4;\n"
"            }\n"
"            /* Specific styling for important labels */\n"
"            QLabel#label_tello_battery, QLabel#label_tello_current_height, QLabel#label_nowtime {\n"
"                font-weight: bold;\n"
"                color: #A3BE8C; /* Nordic green for positive status */\n"
"                font-size: 11pt;\n"
"            }\n"
"            QLabel#label_now_search_name {\n"
"                 font-style: italic;\n"
"                 color: #EBCB8B; /* Nordic yellow for emphasis */\n"
"            }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_tello_battery = QtWidgets.QLabel(self.centralwidget)
        self.label_tello_battery.setObjectName("label_tello_battery")
        self.horizontalLayout_2.addWidget(self.label_tello_battery)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_tello_current_height = QtWidgets.QLabel(self.centralwidget)
        self.label_tello_current_height.setObjectName("label_tello_current_height")
        self.horizontalLayout_2.addWidget(self.label_tello_current_height)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_nowtime = QtWidgets.QLabel(self.centralwidget)
        self.label_nowtime.setObjectName("label_nowtime")
        self.horizontalLayout_2.addWidget(self.label_nowtime)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_img = QtWidgets.QLabel(self.groupBox)
        self.label_img.setMinimumSize(QtCore.QSize(240, 180))
        self.label_img.setMaximumSize(QtCore.QSize(240, 180))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap(":/png/png/v.jpg"))
        self.label_img.setScaledContents(True)
        self.label_img.setObjectName("label_img")
        self.verticalLayout.addWidget(self.label_img)
        self.horizontalLayout_11.addWidget(self.groupBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 7, 0, 7)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(240, 9))
        self.label_2.setMaximumSize(QtCore.QSize(240, 9))
        self.label_2.setLineWidth(0)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/png/near_far_p.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_img_predicted = QtWidgets.QLabel(self.groupBox_2)
        self.label_img_predicted.setMinimumSize(QtCore.QSize(240, 180))
        self.label_img_predicted.setMaximumSize(QtCore.QSize(240, 180))
        self.label_img_predicted.setLineWidth(0)
        self.label_img_predicted.setText("")
        self.label_img_predicted.setPixmap(QtGui.QPixmap(":/png/png/v_depth.jpg"))
        self.label_img_predicted.setScaledContents(True)
        self.label_img_predicted.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_predicted.setIndent(-1)
        self.label_img_predicted.setObjectName("label_img_predicted")
        self.verticalLayout_2.addWidget(self.label_img_predicted)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(130, 0))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_now_search_name = QtWidgets.QLabel(self.groupBox_7)
        self.label_now_search_name.setObjectName("label_now_search_name")
        self.verticalLayout_9.addWidget(self.label_now_search_name)
        self.listWidget_yolo_predcited_items = QtWidgets.QListWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_yolo_predcited_items.sizePolicy().hasHeightForWidth())
        self.listWidget_yolo_predcited_items.setSizePolicy(sizePolicy)
        self.listWidget_yolo_predcited_items.setMinimumSize(QtCore.QSize(220, 180))
        self.listWidget_yolo_predcited_items.setMaximumSize(QtCore.QSize(220, 230))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.listWidget_yolo_predcited_items.setFont(font)
        self.listWidget_yolo_predcited_items.setObjectName("listWidget_yolo_predcited_items")
        self.verticalLayout_9.addWidget(self.listWidget_yolo_predcited_items)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(20, 218, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send.sizePolicy().hasHeightForWidth())
        self.pushButton_send.setSizePolicy(sizePolicy)
        self.pushButton_send.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_send.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_3.addWidget(self.pushButton_send)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.listWidget_llm_query_queue = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_llm_query_queue.sizePolicy().hasHeightForWidth())
        self.listWidget_llm_query_queue.setSizePolicy(sizePolicy)
        self.listWidget_llm_query_queue.setMinimumSize(QtCore.QSize(150, 160))
        self.listWidget_llm_query_queue.setMaximumSize(QtCore.QSize(200, 160))
        self.listWidget_llm_query_queue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget_llm_query_queue.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_llm_query_queue.setObjectName("listWidget_llm_query_queue")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_llm_query_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_llm_query_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_llm_query_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_llm_query_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_llm_query_queue.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidget_llm_query_queue)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.pushButton_clear_llm_query_queue = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clear_llm_query_queue.setObjectName("pushButton_clear_llm_query_queue")
        self.horizontalLayout_5.addWidget(self.pushButton_clear_llm_query_queue)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.listWidget_tello_command_queue = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_tello_command_queue.setMinimumSize(QtCore.QSize(150, 160))
        self.listWidget_tello_command_queue.setMaximumSize(QtCore.QSize(150, 160))
        self.listWidget_tello_command_queue.setObjectName("listWidget_tello_command_queue")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_tello_command_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_tello_command_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_tello_command_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_tello_command_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_tello_command_queue.addItem(item)
        self.horizontalLayout_6.addWidget(self.listWidget_tello_command_queue)
        spacerItem16 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.pushButton_clear_tello_command_queue = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_clear_tello_command_queue.setObjectName("pushButton_clear_tello_command_queue")
        self.horizontalLayout_7.addWidget(self.pushButton_clear_tello_command_queue)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(160, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem19 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.listWidget_yolo_search_queue = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_yolo_search_queue.setMinimumSize(QtCore.QSize(120, 160))
        self.listWidget_yolo_search_queue.setMaximumSize(QtCore.QSize(120, 160))
        self.listWidget_yolo_search_queue.setObjectName("listWidget_yolo_search_queue")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_yolo_search_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_yolo_search_queue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_yolo_search_queue.addItem(item)
        self.horizontalLayout_8.addWidget(self.listWidget_yolo_search_queue)
        spacerItem20 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem21)
        self.pushButton_clear_yolo_search_queue = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_clear_yolo_search_queue.setObjectName("pushButton_clear_yolo_search_queue")
        self.horizontalLayout_9.addWidget(self.pushButton_clear_yolo_search_queue)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem22)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        spacerItem23 = QtWidgets.QSpacerItem(21, 218, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_8.addWidget(self.textBrowser)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit, self.pushButton_send)
        MainWindow.setTabOrder(self.pushButton_send, self.pushButton_clear_llm_query_queue)
        MainWindow.setTabOrder(self.pushButton_clear_llm_query_queue, self.pushButton_clear_tello_command_queue)
        MainWindow.setTabOrder(self.pushButton_clear_tello_command_queue, self.pushButton_clear_yolo_search_queue)
        MainWindow.setTabOrder(self.pushButton_clear_yolo_search_queue, self.listWidget_yolo_search_queue)
        MainWindow.setTabOrder(self.listWidget_yolo_search_queue, self.listWidget_llm_query_queue)
        MainWindow.setTabOrder(self.listWidget_llm_query_queue, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.listWidget_yolo_predcited_items)
        MainWindow.setTabOrder(self.listWidget_yolo_predcited_items, self.listWidget_tello_command_queue)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Large Language Model for Controlling Drones"))
        self.label_5.setText(_translate("MainWindow", "Battery:"))
        self.label_tello_battery.setText(_translate("MainWindow", "80%"))
        self.label_7.setText(_translate("MainWindow", "Flight Altitude:"))
        self.label_tello_current_height.setText(_translate("MainWindow", "100cm"))
        self.label_9.setText(_translate("MainWindow", "Current Time:"))
        self.label_nowtime.setText(_translate("MainWindow", "2024/12/03 14:38:08"))
        self.groupBox.setTitle(_translate("MainWindow", "Drone View"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Recognition View"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Detected Objects"))
        self.label_now_search_name.setText(_translate("MainWindow", "Searching for:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">User</span></p><p><span style=\" color:#ffffff;\">Input</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.label_15.setText(_translate("MainWindow", "Large Language Model       : qwen2.5_0.5b\n"
"Yolo Recognition Model     : yolo11n\n"
"Monocular Depth Estimation : MiDaS"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Language Command Queue"))
        __sortingEnabled = self.listWidget_llm_query_queue.isSortingEnabled()
        self.listWidget_llm_query_queue.setSortingEnabled(False)
        item = self.listWidget_llm_query_queue.item(0)
        item.setText(_translate("MainWindow", "take off now, then rotate counterclockwise 30 degrees, next please move the drone left 5 meters, after that adjust right by 5 feet, subsequently fly to the left for 10 inches, afterwards move the drone backward 1.5 feet."))
        item = self.listWidget_llm_query_queue.item(1)
        item.setText(_translate("MainWindow", "Could you please ensure that the current object search task list is cleared, as it might interfere with the new operations?"))
        item = self.listWidget_llm_query_queue.item(2)
        item.setText(_translate("MainWindow", "Turn the drone 90 degrees to the left"))
        item = self.listWidget_llm_query_queue.item(3)
        item.setText(_translate("MainWindow", "Ascend 1 foot, then move left by 2 feet, afterwards can we fly it forward a bit?"))
        item = self.listWidget_llm_query_queue.item(4)
        item.setText(_translate("MainWindow", "Could you kindly check if the fanta, kite, and toothbrush are somewhere nearby?"))
        self.listWidget_llm_query_queue.setSortingEnabled(__sortingEnabled)
        self.pushButton_clear_llm_query_queue.setText(_translate("MainWindow", "Clear Queue"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Control Command Queue"))
        __sortingEnabled = self.listWidget_tello_command_queue.isSortingEnabled()
        self.listWidget_tello_command_queue.setSortingEnabled(False)
        item = self.listWidget_tello_command_queue.item(0)
        item.setText(_translate("MainWindow", "turn_right 180 degrees"))
        item = self.listWidget_tello_command_queue.item(1)
        item.setText(_translate("MainWindow", "move_left 3 in"))
        item = self.listWidget_tello_command_queue.item(2)
        item.setText(_translate("MainWindow", "move_back 10 ft"))
        item = self.listWidget_tello_command_queue.item(3)
        item.setText(_translate("MainWindow", "move_up 40 cm"))
        item = self.listWidget_tello_command_queue.item(4)
        item.setText(_translate("MainWindow", "turn_right 45 degrees"))
        self.listWidget_tello_command_queue.setSortingEnabled(__sortingEnabled)
        self.pushButton_clear_tello_command_queue.setText(_translate("MainWindow", "Clear Queue"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Object Search Queue"))
        __sortingEnabled = self.listWidget_yolo_search_queue.isSortingEnabled()
        self.listWidget_yolo_search_queue.setSortingEnabled(False)
        item = self.listWidget_yolo_search_queue.item(0)
        item.setText(_translate("MainWindow", "cola"))
        item = self.listWidget_yolo_search_queue.item(1)
        item.setText(_translate("MainWindow", "fanta"))
        item = self.listWidget_yolo_search_queue.item(2)
        item.setText(_translate("MainWindow", "sprite"))
        self.listWidget_yolo_search_queue.setSortingEnabled(__sortingEnabled)
        self.pushButton_clear_yolo_search_queue.setText(_translate("MainWindow", "Clear Queue"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Log"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:25:54 - [app] llm_query_queue.put(take off drone)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:25:55 - [llm_query_thread] res: {\'type\': \'Flight Control Command Task\', \'commend\': \'take_off.\'}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:00 - [app] llm_query_queue.put(Can you help me find coldrex)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:01 - [llm_query_thread] res: {\'type\': \'Search Task\', \'commend\': \'coldrex.\'}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:01 - [search_thread] The current searched item is: coldrex</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:01 - [adjust_drone] Object detected, current object x:0.6%, y:0.5%, occupies 0.1% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:01 - [adjust_drone] Not detected: Turn right 60 degrees.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:02 - [tello_control_thread] Flight control command executed successfully: &quot;take_off&quot;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:06 - [adjust_drone] Object detected, current object x:0.22%, y:0.27%, occupies 0.006% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:06 - [adjust_drone] Object detected: coldrex, PID adjustment in progress.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:06 - [adjust_drone] PID control: Turn left 15 degrees.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:07 - [adjust_drone] Object detected, current object x:0.41%, y:0.28%, occupies 0.005% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:07 - [adjust_drone] PID control: up 9 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:11 - [adjust_drone] Object detected, current object x:0.4%, y:0.37%, occupies 0.009% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:11 - [adjust_drone] PID control: Move forward 38 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:13 - [adjust_drone] Object detected, current object x:0.32%, y:0.42%, occupies 0.024% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:13 - [adjust_drone] Object detected, current object x:0.3%, y:0.43%, occupies 0.028% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:13 - [adjust_drone] Object detected: coldrex, PID adjustment in progress.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:13 - [adjust_drone] PID control: Turn left 10 degrees.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:14 - [adjust_drone] Object detected, current object x:0.43%, y:0.43%, occupies 0.026% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:14 - [adjust_drone] PID control: up 5 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:19 - [adjust_drone] Object detected, current object x:0.45%, y:0.53%, occupies 0.022% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:19 - [adjust_drone] PID control: Move forward 10 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:23 - [adjust_drone] Object detected, current object x:0.42%, y:0.58%, occupies 0.035% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:23 - [adjust_drone] Object detected, current object x:0.42%, y:0.59%, occupies 0.036% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:23 - [adjust_drone] Object detected: coldrex, PID adjustment in progress.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:23 - [adjust_drone] PID control: Turn left 4 degrees.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:24 - [adjust_drone] Object detected, current object x:0.45%, y:0.6%, occupies 0.036% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:24 - [adjust_drone] PID control: down 5 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:28 - [adjust_drone] Object detected, current object x:0.43%, y:0.51%, occupies 0.037% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:28 - [adjust_drone] PID control: Move forward 5 cm.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:33 - [adjust_drone] Object detected, current object x:0.4%, y:0.61%, occupies 0.045% of the area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:33 - [adjust_drone] Target is approaching, hovering...</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:44 - [app] llm_query_queue.put(land)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:44 - [llm_query_thread] res: {\'type\': \'Flight Control Command Task\', \'commend\': \'land.\'}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2025-06-25 15:26:48 - [tello_control_thread] Flight control command executed successfully: &quot;land&quot;</p></body></html>"))
from res import app_rc
